# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.4

EAPI="5"

PYTHON_COMPAT=( python2_7 )

inherit distutils-r1


DESCRIPTION="etcd-cli CLI for Etcd based on schemas"
HOMEPAGE="https://github.com/mickep76/etcd-cli.git"
SRC_URI="mirror://pypi/e/etcd-cli/${P}.tar.gz"

LICENSE="Apache-2.0"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND="dev-python/configparser
	dev-python/jinja
	dev-python/logging
	dev-python/python-etcd
	dev-python/pyyaml
	dev-python/setuptools
	dev-python/simplejson"




